ITEM.name = "Suitcase"
ITEM.desc = "A small brown suitcase for extra storage."
ITEM.model = "models/props_c17/suitcase_passenger_physics.mdl"
ITEM.width = 3
ITEM.height = 2
ITEM.invWidth = 5
ITEM.invHeight = 3
ITEM.price = 100
ITEM.category = "Storage"
ITEM.permit = "misc"